
import React from 'react';
import { ActionPlan } from '../types';
import { Shield, AlertTriangle, Printer, X } from 'lucide-react';

interface Props {
  plan: ActionPlan;
  onClose: () => void;
}

const ActionPlanPrint: React.FC<Props> = ({ plan, onClose }) => {
  
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-[100] bg-slate-900/90 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-white w-full max-w-4xl h-[90vh] flex flex-col rounded-xl shadow-2xl overflow-hidden">
        
        {/* Toolbar - Hidden when printing */}
        <div className="bg-slate-100 p-4 border-b border-slate-200 flex justify-between items-center print:hidden">
          <h3 className="font-bold text-slate-700">Generated Strategic Assessment</h3>
          <div className="flex gap-3">
            <button 
              onClick={handlePrint}
              className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-bold text-sm"
            >
              <Printer size={16} /> Print / Save PDF
            </button>
            <button 
              onClick={onClose}
              className="p-2 text-slate-500 hover:bg-slate-200 rounded-lg"
            >
              <X size={20} />
            </button>
          </div>
        </div>

        {/* Printable Content Area */}
        <div className="flex-1 overflow-y-auto p-8 md:p-12 print:p-0 print:overflow-visible" id="print-area">
          
          {/* Header */}
          <div className="border-b-4 border-slate-900 pb-6 mb-8">
            <div className="flex justify-between items-start">
              <div>
                <h1 className="text-3xl font-serif font-bold text-slate-900">STRATEGIC ACTION PLAN</h1>
                <p className="text-slate-500 uppercase tracking-widest text-xs mt-2 font-bold">Project 213 • Philippine Custody Recovery</p>
              </div>
              <div className="text-right">
                <div className="bg-red-600 text-white text-xs font-bold px-3 py-1 uppercase inline-block">Confidential</div>
                <p className="text-xs text-slate-400 mt-2">Generated by AI • Verify with Counsel</p>
              </div>
            </div>
          </div>

          {/* Risk Section */}
          <div className="mb-8">
            <h2 className="text-sm font-bold text-slate-400 uppercase tracking-wide mb-3 flex items-center gap-2">
              <AlertTriangle size={16} className="text-red-500"/> Risk Assessment
            </h2>
            <div className="bg-slate-50 p-6 border-l-4 border-red-500 text-slate-800 leading-relaxed font-serif">
              {plan.riskAssessment}
            </div>
          </div>

          <div className="grid md:grid-cols-2 gap-8">
            {/* Immediate Actions */}
            <div>
               <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wide mb-4 border-b border-slate-200 pb-2">
                 Immediate Tactical Actions
               </h2>
               <ul className="space-y-3">
                 {plan.immediateActions.map((item, i) => (
                   <li key={i} className="flex items-start gap-3 text-sm text-slate-700">
                     <span className="font-bold text-slate-300">0{i+1}</span>
                     <span>{item}</span>
                   </li>
                 ))}
               </ul>
            </div>

            {/* Resources */}
            <div>
               <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wide mb-4 border-b border-slate-200 pb-2">
                 Required Resources
               </h2>
               <ul className="space-y-3">
                 {plan.requiredResources.map((item, i) => (
                   <li key={i} className="flex items-start gap-3 text-sm text-slate-700">
                     <div className="w-1.5 h-1.5 bg-slate-900 rounded-full mt-1.5"></div>
                     <span>{item}</span>
                   </li>
                 ))}
               </ul>
            </div>
          </div>

          {/* Long Term Strategy */}
          <div className="mt-8 pt-8 border-t border-slate-200">
             <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wide mb-4">
                 Long-Term Legal Strategy
             </h2>
             <div className="space-y-4">
                {plan.legalStrategy.map((item, i) => (
                   <div key={i} className="flex items-start gap-4">
                     <Shield size={18} className="text-slate-400 shrink-0 mt-0.5" />
                     <p className="text-slate-700 text-sm leading-relaxed">{item}</p>
                   </div>
                ))}
             </div>
          </div>

           {/* Goals */}
           <div className="mt-8 bg-slate-900 text-white p-6 rounded-lg print:bg-white print:text-black print:border print:border-slate-300">
             <h2 className="text-sm font-bold text-slate-400 uppercase tracking-wide mb-4 print:text-black">
                 Strategic Objectives
             </h2>
             <ul className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {plan.longTermGoals.map((item, i) => (
                   <li key={i} className="flex items-center gap-2 text-sm">
                      <div className="w-2 h-2 bg-green-500 rounded-full print:bg-black"></div>
                      {item}
                   </li>
                ))}
             </ul>
          </div>

          <div className="mt-12 pt-6 border-t border-slate-200 text-center">
             <p className="text-[10px] text-slate-400 max-w-2xl mx-auto">
               DISCLAIMER: This document was generated by an AI assistant based on user inputs. It does not constitute legal advice. Philippine Family Law is complex. 
               Article 213 and Article 176 provisions require interpretation by a licensed attorney in the Philippines.
             </p>
          </div>

        </div>
      </div>

      <style>{`
        @media print {
          body * {
            visibility: hidden;
          }
          #print-area, #print-area * {
            visibility: visible;
          }
          #print-area {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
            margin: 0;
            padding: 20px;
            overflow: visible !important;
          }
        }
      `}</style>
    </div>
  );
};

export default ActionPlanPrint;
